"""Migrating users, companies, orders, products, reviews

Revision ID: 2529b497a6d0
Revises: 41a601a0b799
Create Date: 2024-07-09 12:15:04.352250

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '2529b497a6d0'
down_revision = '41a601a0b799'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('orders', schema=None) as batch_op:
        batch_op.drop_column('total_price')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('orders', schema=None) as batch_op:
        batch_op.add_column(sa.Column('total_price', mysql.FLOAT(), nullable=False))

    # ### end Alembic commands ###
