"""Migrating users, companies, orders, products, reviews

Revision ID: 41260681afda
Revises: 2c95669af3c0
Create Date: 2024-07-02 14:02:27.124765

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '41260681afda'
down_revision = '2c95669af3c0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('user_type')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_type', mysql.VARCHAR(length=50), nullable=False))

    # ### end Alembic commands ###
